endroid_qr_code:
    default:
        writer: Endroid\QrCode\Writer\PngWriter
        size: 50
        margin: 0
        encoding: 'UTF-8'
        errorCorrectionLevel: 'low'
        roundBlockSizeMode: 'none'
        validateResult: false
