twig:
    default_path: '%kernel.project_dir%/templates'
    # On déclare bootstrap dans twig
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        entreprise: '%env(ENTREPRISE)%'
        repCanChooseMeetingHour: '%env(bool:REP_CAN_CHOOSE_MEETING_HOUR)%'
    file_name_pattern: '*.twig'

when@test:
    twig:
        strict_variables: true
