twig:
    default_path: '%kernel.project_dir%/templates'
    # On déclare bootstrap dans twig
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        APP_VERSION: '%env(VERSION)%'

when@test:
    twig:
        strict_variables: true
